### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by BigMartin58** [pufmat/attributesmod#10]
Minecraft 1.18.2 Forge Version 40.2.14 Mod Version 0.6.0

I am [crashing](https://api.mclo.gs/1/raw/xhvaxG1) on launch. I'm not familiar enough with the log to identify the cause. Version 0.5.0 starts just fine.

**Comment by pufmat** [comment]
Thanks for reporting. The issue is caused by Apotheosis because it replaces part of the game code to which my mod tries to inject. I will see what can be done to fix it.

**Comment by pufmat** [comment]
Apotheosis for 1.18.2 is no longer maintained. I'll probably make a workaround so it doesn't cause crash, but Protection Shred attribute won't be working.

**Comment by Zeadrasil** [comment]
There appears to be a similar issue with Iron's Spells and Spellbooks with what I believe is the Armor Shred attribute, from a look at the [error message](https://pastebin.com/JFju2dcv). I was able to determine that it was Iron's Spells and Spellbooks because that was the only other mod on the install.

**Comment by pufmat** [comment]
Fixed in the latest version.
